### ISSUE TITLE
[BE] API 설계

### ISSUE THREAD

**Issue by llcodingll** [donga-it-club/past-foward-backend#2]
BE API 설계

**Comment by Minseok-2001** [comment]
| Endpoint| HTTP method| Description|
|--------|--------|--------|
| /surveys/{surveyId}/responses| POST | 설문 응답 제출|
| /surveys| GET| 설문조사 조회 |
| /retrospectives| GET| 회고 리스트 반환 (필터 로직 필요)|
| /retrospectives| POST | image upload 가능하려면 S3가 필요할 수도 있을 것 같습니다.|
| /retrospectives | PUT | 회고 정보 수정| 
| /retrospectives | PUT | 회고 삭제| 
| /retrospectives/{retrospectiveId}/sections/{sectionId}| POST | 특정 섹션 추가| 
| /retrospectives/{retrospectiveId}/sections/{sectionId} | PUT | 특정 섹션 내용 수정| 
| /retrospectives/{retrospectiveId}/sections/{sectionId}| DELETE | 특정 섹션 삭제| 
| /retrospectives/{retrospectiveId}/sections/{sectionId}/comments| POST | 특정 섹션 내 댓글 추가| 
| /retrospectives/{retrospectiveId}/sections/{sectionId}/likes| POST | 특정 세션 좋아요 기능| 
| /retrospectives/{retrospectiveId}/invitation-link| GET| 초대 링크 |

**Comment by Minseok-2001** [comment]
@llcodingll 윤지님 궁금한 점이 있어 문의드립니다!
혹시 
/retrospectives/{retrospectiveId}/link

이거 공유링크 적어주신 부분 기능이 혹시 짧게 url을 변환해야하는 요구사항이 있을까요? ex) bitly

**Comment by llcodingll** [comment]
@Minseok-2001
아뇨! 아직 그런 요구사항은 없습니다!(기획팀에서 기획 진행 중인 상태라 제대로 이야기가 나오지 않아서 미정인 상태입니다.)
혹시 url이 많이 지저분하게 나오거나 변환하는 작업이 많이 어려울 것을 걱정하셔서 물어보신 건지 궁금해요!

**Comment by yanggak12** [comment]
이 이슈 티켓은 API 설계 정도로 진행하시고
API 명세서는 위키로 이동하는게 좋을 것 같아요.

**Comment by yanggak12** [comment]
백엔드 레포지토리 위키에 등록해주세요!

**Comment by Minseok-2001** [comment]
넵! 아직 확정되지 않아서 (draft라고 보는 것이 맞을 것 같습니다!)
금일 회의때 정확히 리스트업하고 결정되면 위키에 등록해두도록 하겠습니다!!

**Comment by Minseok-2001** [comment]
> 혹시 url이 많이 지저분하게 나오거나 변환하는 작업이 많이 어려울 것을 걱정하셔서 물어보신 건지 궁금해요!

앗 그런 것은 아니고 그냥 궁금증으로 여쭤봤습니다!
